### PR TITLE
Require Node.js 12 and move to ESM

### PR DESCRIPTION
**Pull request by jimmywarting**
Require Node.js 12 and move to ESM

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why close?

**Comment by jimmywarting** [comment]
I accidentally sent a duplicate PR, one of this has already been accepted :)

**Comment by sindresorhus** [comment]
Oh, LOL. Right.

**Comment by jimmywarting** [comment]
if you have any other project i can help you out with converting to ESM then let me know
give me 1-4 options (repos) so i can choose the one i feel comfortable working in and i will send you a PR :)

**Pull request closed without merging**
